# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MdjwaUoM-YLR3rZysXdIrNlCWlkYEccO
"""

import requests
import json
import pandas as pd

#What happens when what you are looking for doesn't exist?
response = requests.get("https://chroniclingamerica.loc.gov/this-api-doesnt-exist")
print(response.status_code)

#Get json file of your search and check status
#First 20 search results
response20 = requests.get("https://chroniclingamerica.loc.gov/search/pages/results/?state=Wisconsin&dateFilterType=yearRange&date1=1914&date2=1918&sort=date&andtext=war&sequence=1&format=json")
print(response20.status_code)
# Turn file into a python dictionary
data = response20.json()
#Save a copy of the first 20 results
with open('corpusraw.txt', 'w') as corpusraw_file:
     corpusraw_file.write(json.dumps(data))

#Deal with dictionaries within lists
d = data.get('items')
newspaper1 = d[0]
idnewspaper1 = newspaper1.get('id')
print(idnewspaper1)