# -*- coding: utf-8 -*-
"""Preparing and Preprocessing Your Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mjcaup5lJgBSZ3kOJBxa7zZg6ITpCJAv
"""
from pathlib import Path

def create_file_list(directory, filter_str='*'):
  files = Path(directory).glob(filter_str)
  files_to_analyze = list(map(str, files))
  return files_to_analyze

corpus_dir = './books'
corpus_file_list = create_file_list(corpus_dir)
print(corpus_file_list)

austen_list = create_file_list(corpus_dir, 'austen*')
print(*austen_list, sep='\n')

preview_len = 290
emmapath = create_file_list(corpus_dir, 'austen-emma*')[0]
print(emmapath)
sentence = ""
with open(emmapath, 'r') as f:
  sentence = f.read(preview_len)[50:preview_len]

print(sentence)